version: '3.8'
services:
  logger-server:
    image: dev1800/logger:latest
    build:
      context: .
    volumes:
      - ./:/app
      - /app/node_modules
    deploy:
      replicas: 4
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 2
        delay: 10s
    environment:
      - PORT=5000
    depends_on:
      - logger-nginx
      - logger-elastic

  logger-elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.10.2
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node
    volumes:
      - logger-elastic:/usr/share/elasticsearch/data
    
  kibana:
    image: docker.elastic.co/kibana/kibana-oss:7.10.2
    depends_on:
      - logger-elastic 
      - logger-nginx
      - logger-server

    ports:
      - "5601:5601"
    environment:
      - 'ELASTICSEARCH_HOSTS=["http://logger-elastic:9200"]'

  logger-nginx:
    image: nginx:stable-alpine
    container_name: logger-nginx-c 
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "5000:80"

volumes:
  logger-elastic:
      
